# theme: jekyll-theme-cayman

# Site settings
title: WHQ Blog
SEOTitle: 王海全的博客 | WHQ's Blog
header-img: img/bg-1.jpg
email: whq311@foxmail.com
description: "博士 | 王海全，PhD Cracker"
keyword: "wanghaiquan, whq, dr-whq, PhD"
url: "https://dr-whq.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# avatar and Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: favicon.ico


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "PhD Cracker"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# SNS settings
RSS: false
weibo_username:     false
zhihu_username:     false
github_username:    dr-whq


# Build settings
paginate: 10
plugins: [jekyll-paginate]
# gems: [jekyll-paginate]


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 10ac9a881ac9818773d5                            #生成的clientID
  clientSecret: c9db677b9952e9326236928861c2de49a5bd8118    #生成的clientSecret
  repo: dr-whq.github.io    #仓库名称
  owner: dr-whq    #github用户名
  admin: dr-whq
  # distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Friends
friends: [
  {
    title: "xxxxxx2's blog",
    href: "https://dr-whq.github.io/"
  },
  {
    title: "xxxxxx1's blog",
    href: "https://dr-whq.github.io/"
  }
]
